[tool.poetry]
name = "djplus"
version = "0.1.0"
description = ""
authors = ["githashem <PersonalHashem@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.3"

[tool.poetry.dev-dependencies]
django-debug-toolbar = "^3.2.4"

[tool.poetry.script]
djplus = "djplus.__main__:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
