name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: dropdown
    attributes:
      label: Which app is the source of the bug?
      options:
        - auth
        - admin
        - blog
        - shop
        - payment
        - storage
        - academy
        - forum
        - contact
        - command line
        - project template
        - project
        - other/I don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened instead?
    validations:
      required: true

  - type: input
    attributes:
      label: Jommerce version?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
