name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: dropdown
    attributes:
      label: Which app is the source of the bug?
      options:
        - command-line/project template/app template
        - templates/static
        - auth
        - other/i don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: What should happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What happened instead?
    validations:
      required: true

  - type: input
    attributes:
      label: Djplus version?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
