name: Bug Report
description: Create a report to help us improve
labels: ["bug"]

body:
  - type: dropdown
    attributes:
      label: Which app is the source of the bug?
      options:
        - command-line/project-template
        - auth
        - other/i don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: What Bug?
      description: Tell us what should happen and what happened instead
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: Djplus version? Python version? Django version? browser type? ...
    validations:
      required: true
