name: Documentation
description: Suggest edits for the Jommerce documentation
labels: ["documentation"]

body:
  - type: dropdown
    attributes:
      label: Which part of Jommerce documentation?
      options:
        - command-line/project template/app template
        - templates/static
        - auth
        - admin
        - blog
        - shop
        - other/i don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: Details
    validations:
      required: true
