name: Feature Request
description: Suggest an idea for improving Djplus
labels: ["enhancement"]

body:
  - type: dropdown
    attributes:
      label: Which app is relevant/related to the feature request?
      options:
        - command-line/project-template
        - auth
        - other/i don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: What feature?
      description: A clear and concise description of what you want to happen
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why?
      description: Why is this change important to you? How would you use it? How can it benefit other users?
    validations:
      required: true
