name: Feature Request
description: Suggest an idea for improving Djplus
labels: ["enhancement"]

body:
  - type: dropdown
    attributes:
      label: Which app is relevant/related to the feature request?
      options:
        - command-line/project template/app template
        - templates/static
        - auth
        - admin
        - blog
        - shop
        - other/i don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen
    validations:
      required: true
