name: Feature Request
description: Suggest an idea for improving Jommerce
labels: ["enhancement"]

body:
  - type: dropdown
    attributes:
      label: Which app is relevant/related to the feature request?
      options:
        - auth
        - admin
        - blog
        - shop
        - payment
        - storage
        - academy
        - forum
        - contact
        - command line
        - project template
        - project
        - other/I don't know
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      description: A clear and concise description of what you want to happen
    validations:
      required: true
