name: Localization
description: Localizing Jommerce apps
labels: ["localization"]

body:
  - type: dropdown
    attributes:
      label: Which one of the Jommerce sections?
      options:
        - command-line/project template/app template
        - templates/static
        - auth
        - admin
        - blog
        - shop
        - other/i don't know
    validations:
      required: true

  - type: input
    attributes:
      label: What languages?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
