name: Localization
description: Localizing Jommerce apps
labels: ["localization"]

body:
  - type: dropdown
    attributes:
      label: Which one of the Jommerce sections?
      options:
        - auth
        - admin
        - blog
        - shop
        - payment
        - storage
        - academy
        - forum
        - contact
        - command line
        - project template
        - project
        - other/I don't know
    validations:
      required: true

  - type: input
    attributes:
      label: What languages?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
